module.exports = Object.freeze({
    EMAIL_IS_EMPTY: 'EMAIL_IS_EMPTY',
    PASSWORD_IS_EMPTY: 'PASSWORD_IS_EMPTY',
    PASSWORD_LENGTH_MUST_BE_MORE_THAN_8: 'PASSWORD_LENGTH_MUST_BE_MORE_THAN_8',
    WRONG_PASSWORD: 'WRONG_PASSWORD',
    SOME_THING_WENT_WRONG: 'SOME_THING_WENT_WRONG',
    USER_EXISTS_ALREADY_WITH_USER_NAME: 'USER_EXISTS_ALREADY_WITH_USER_NAME',
    USER_EXISTS_ALREADY_WITH_EMAIL: 'USER_EXISTS_ALREADY_WITH_EMAIL',
    USER_EXISTS_ALREADY_WITH_PHONE_NUMBER: 'USER_EXISTS_ALREADY_WITH_PHONE_NUMBER',
    USER_DOES_NOT_EXIST: 'USER_DOES_NOT_EXIST',
    TOKEN_IS_EMPTY: 'TOKEN_IS_EMPTY',
    EMAIL_IS_IN_WRONG_FORMAT: 'EMAIL_IS_IN_WRONG_FORMAT',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    DOCTOR_LOGIN_INPUTS_INVALID: "DOCTOR_LOGIN_INPUTS_INVALID",

    DOCTOR_CREATION_SUCCESSFULL: 'DOCTOR_CREATION_SUCCESSFULL',
    DOCTOR_LOGIN_SUCCESSFULL: 'DOCTOR_LOGIN_SUCCESSFULL',
    PASWWORD_DOES_NOT_MATCH_WITH_CONFIRM_PASSWORD: 'PASWWORD_DOES_NOT_MATCH_WITH_CONFIRM_PASSWORD',

    PATIENT_NOT_EXISTS: "PATIENT_NOT_EXISTS",
    DOCTOR_NOT_EXISTS: "DOCTOR_NOT_EXISTS",
    REPORT_STATUS_INVALID: "REPORT_STATUS_INVALID",


    PATIENT_CREATION_SUCCESSFULL: 'PATIENT_CREATION_SUCCESSFULL',

    ALLOWED_STATUS: ["Negative", "Travelled-Quarantine", "Symptoms-Quarantine", "Positive-Admit"],

    SALT_ROUND: 10,
    JWT_SECRET_KEY: "qwertyusdfghzxcvb"
}) 